# Generated by Django 2.2.1 on 2019-06-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_by', models.CharField(max_length=30)),
                ('comment_at', models.DateTimeField(auto_now_add=True)),
                ('comment_content', models.TextField()),
                ('comment_on', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=30)),
                ('post_content', models.TextField()),
                ('post_created_by', models.CharField(max_length=30)),
                ('post_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
